# Generated by Django 4.0.4 on 2022-04-15 10:38

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('pid', models.IntegerField(primary_key=b'I01\n', serialize=False)),
                ('p_name', models.CharField(max_length=200)),
                ('p_link', models.FilePathField(path=pathlib.PurePosixPath('/Users/saurabh/Desktop/Online Judge/judge/static/problems'))),
                ('p_input', models.FilePathField(path=pathlib.PurePosixPath('/Users/saurabh/Desktop/Online Judge/judge/static/problem_input'))),
                ('p_output', models.FilePathField(path=pathlib.PurePosixPath('/Users/saurabh/Desktop/Online Judge/judge/static/problem_ouput'))),
                ('p_submitted', models.CharField(max_length=200)),
                ('p_accepted', models.IntegerField()),
                ('p_level', models.CharField(max_length=10)),
                ('p_editorial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(default=1)),
                ('attempt_id', models.IntegerField(default=1)),
                ('attempt_pid', models.IntegerField(default=1)),
                ('attempt_username', models.IntegerField(default='')),
                ('attempt_verdict', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
